### ISSUE TITLE
Add support for specifying an index

### ISSUE THREAD

**Issue by dgolub** [mongodb-labs/mongo-csharp-search#1]

**Comment by MarcusSorealheis** [comment]
Can you link to the PR that resolved this issue?

**Comment by MarcusSorealheis** [comment]
Is this it: [45a70b1b33d67b5a29018faa845d82a665eee208](https://github.com/mongodb-labs/mongo-csharp-search/commit/45a70b1b33d67b5a29018faa845d82a665eee208) ?

**Comment by dgolub** [comment]
Yes, that's it.
