### ISSUE TITLE
Score definition

### ISSUE THREAD

**Issue by ghendo** [mongodb-labs/mongo-csharp-search#14]
When I use an Autocomplete as below

searches.Add(SearchBuilders<T>.Search.Autocomplete(fieldValues, item,AutocompleteTokenOrder.Any, fuzzyOptions, scoreDefinition.Constant(0)));

This crashes as wont allow score definition of zero

**Comment by ghendo** [comment]
extra detail
From talking to Mongo support they say
regular constant doesnt support zero but function constant does.
So      { "constant": { "value": 0 }}       is not supported
But    { "function":{ "constant": 0 }}    is supported
Does this package support this type of  score definition?

**Comment by dgolub** [comment]
Unfortunately, not yet.  I've filed an internal ticket to add this feature, most likely in a 1.1 release.
