### ISSUE TITLE
Range operator with compound

### ISSUE THREAD

**Issue by ghendo** [mongodb-labs/mongo-csharp-search#17]
I cant seem to add a Range operator with a compound operator
Current search
`  var pipelineSearch1 = new EmptyPipelineDefinition<EmailMessagePreciseEntity>();
  var pipelineData = pipelineSearch1
      .Search(SearchBuilders<EmailMessagePreciseEntity>.Search
          .Compound()
              .Must(nearFilter)
              .Filter(matches)
              .Should(searches)
              .MinimumShouldMatch(minShouldMatch)
          , null,
          "PreciseEmailEntity",
          countOptions,
          false
          )
      .Facet(fac2, fac3)
      ;`

Tried in the compound and before compound but neither works

**Comment by dgolub** [comment]
Atlas Search functionality based on this extension was recently incorporated into version 2.19 of the C# driver.  Hence, if you upgrade your driver, this extension is no longer needed.  You can try upgrading and see if the problem persists.  If it does, it would be best to file a bug report in the CSHARP project on [MongoDB JIRA](https://jira.mongodb.org).
