### ISSUE TITLE
Please Add Support for "Numeric" types to "Equals" operator

### ISSUE THREAD

**Issue by ggaldamesd** [mongodb-labs/mongo-csharp-search#19]
Hi!, now Atlas Search supports numeric data types with the equals operator, please add support to this library, you can get more information on this official link from Atlas: https://www.mongodb.com/docs/atlas/atlas-search/equals/

Thanks in advance!,

Gerardo.

**Comment by dgolub** [comment]
Thanks for submitting this!  The functionality in this extension library has been incorporated into recent versions of the C# driver.  Therefore, the extension is now deprecated and will not be receiving any new features going forward.  If you would like to submit a feature request for the C# driver, you can do so in the CSHARP project on [MongoDB JIRA](https://jira.mongodb.org).
