### ISSUE TITLE
Please Add Support for "knnBeta" operator on "$search" stage, this operator works with "Vector Fields" for "Word Embbedings".

### ISSUE THREAD

**Issue by ggaldamesd** [mongodb-labs/mongo-csharp-search#20]
Hi!, now Atlas Search supports searchs with "Vector Fields" (Word Embbedings) data types with the new "KnnBeta" operator, this features will help us to work with LLM models and AI solutions, please add support to this library, you can get more information on this official link from Atlas: https://www.mongodb.com/docs/atlas/atlas-search/field-types/knn-vector/

Thanks in advance!,

Gerardo.

**Comment by dgolub** [comment]
Thanks for submitting this!  The functionality in this extension library has been incorporated into recent versions of the C# driver.  Therefore, the extension is now deprecated and will not be receiving any new features going forward.  If you would like to submit a feature request for the C# driver, you can do so in the CSHARP project on [MongoDB JIRA](https://jira.mongodb.org).
